'use strict';

module.exports = {
    NUM_ATTEMPTS_ALLOWED: 3,
    NUM_ATTEMPTS_TIMEFRAME: 1,
    PASSWORD_HISTORY_UPTILL: 3,
    PASSWORD_EXPIRES_IN_MONTHS: 6,
    REMINDER_DAYS_BEFORE_PASSWORD_EXPIRES:  3,
    RESET_TOKEN_EXPIRES_IN_HOURS: 1,
    REMINDER_CONSECUTIVE_SPAN: 2
};
