module.exports = {
	SEARCH : "search/",
	GET_MOVIE_DETAILS: 'getdetails/',
	ADD_TO_WISHLIST: 'addtowishlist/',
	GET_WISHLIST: 'getmywishlist/',
	REMOVE_FROM_WISHLIST: 'removefromwishlist/',
	LOGIN: 'login',
	USER_REGISTRATION: 'register/',
	TRENDING_MOVIES: 'trendingmovies/',
	LOG_OUT: 'logout',
	GET_MY_SHOWS: 'getmyshows/',
	ADD_SHOW: 'addshow/',
	UPCOMING_SHOWS: 'getupcomingshows/',
	CANCEL_SHOW: 'cancelshow',
	ADD_SCREEN: 'addscreen',
	REMOVE_SCREEN: 'removescreen',
	USER_INFO: 'userprofile',
}